### PR TITLE
Attempted v102 Compatibility

### PR DESCRIPTION
**Pull request by EnigmaPatrick**
I've made tweaks based on the guide; https://developer.thunderbird.net/add-ons/updating/tb102/adapt-to-changes-in-thunderbird-92-102#nsifolderlistener

Having tested briefly alerts seem to be working as expected.

### CODE REVIEW

**Comment by EnigmaPatrick** [comment]
Only actual code changes for mailboxalertOverlay.js were replacing; 

OnItemAdded -> OnMessageAdded

**Comment by mhalano** [comment]
I cloned your repository and built a .xpi file using the `create.sh` script. I installed the new extension, but the configuration I had, sound and message when a new email arrives to inbox, didn't seem to work

**Comment by mhalano** [comment]
I got this error. My message uses `notify-send` command
image

**Comment by mhalano** [comment]
The sound is ok, but there is no message (using the default message option)

**Comment by EnigmaPatrick** [comment]
@mhalano 
Try this, not sure why yours isn't building
[mailboxalert-0.30.xpi.zip](https://github.com/tjeb/Mailbox-Alert/files/9010613/mailboxalert-0.30.xpi.zip)

**Comment by mhalano** [comment]
> @mhalano Try this, not sure why yours isn't building [mailboxalert-0.30.xpi.zip](https://github.com/tjeb/Mailbox-Alert/files/9010613/mailboxalert-0.30.xpi.zip)

This file seems corrupt. The add-on I made using `create.sh` script was recognized correctly.

**Comment by EnigmaPatrick** [comment]
> > @mhalano Try this, not sure why yours isn't building [mailboxalert-0.30.xpi.zip](https://github.com/tjeb/Mailbox-Alert/files/9010613/mailboxalert-0.30.xpi.zip)
> 
> This file seems corrupt. The add-on I made using `create.sh` script was recognized correctly.

Did you unzip the file? Has to be .xpi to import.

**Comment by mhalano** [comment]
> > > @mhalano Try this, not sure why yours isn't building [mailboxalert-0.30.xpi.zip](https://github.com/tjeb/Mailbox-Alert/files/9010613/mailboxalert-0.30.xpi.zip)
> > 
> > 
> > This file seems corrupt. The add-on I made using `create.sh` script was recognized correctly.
> 
> Did you unzip the file? Has to be .xpi to import.

I did not. My file worked fine. 
[mailbox-alert-0.30-mhalano.xpi.zip](https://github.com/tjeb/Mailbox-Alert/files/9010741/mailbox-alert-0.30-mhalano.xpi.zip)

**Comment by EnigmaPatrick** [comment]
Did you get the notify-send issue resolved on your build? As my build here is working as expected with the .zip I uploaded. If you unzip that and install it into thunderbird it should work.

**Comment by mhalano** [comment]
You zipped the .xpi file. I didn't see that. I will try your version

**Comment by mhalano** [comment]
Still getting the problem with notify-send, even with your version.

**Comment by EnigmaPatrick** [comment]
Looks like that might actually be something to do with your config;

(https://tjeb.nl/Projects/Mailbox_Alert/)
> If you don't like the default system messages, you can use libnotify (Thanks for the tip, Alf :) ) to show new mail arrived:

> /usr/bin/notify-send -i /usr/share/pixmaps/mozilla-thunderbird.xpm %sendername\ %folder %subject

I'd look at your alert settings and see if you're calling /usr/bin/notify-send to verify.

**Comment by mhalano** [comment]
Found the problem: I'm using the Snap version and I can't acess /usr/bin. But the native message still fails

**Comment by EnigmaPatrick** [comment]
Ah I see, well I guess if you just tweak your alerts to not use /usr/bin/notify-send then it wouldn't prompt the error. 

As I'm running on windows I can't really replicate the issue here.

**Comment by tjeb** [comment]
Hey, thanks for the PR! I have not merged it directly, as the commit removed a lot of whitespace, but I have taken the relevant changes for the listener. I also just fixed another issue with 102. Will do some more testing here over the weekend and then submit a new release.

**Comment by siffegh** [comment]
> new release

Hoping that contains https://github.com/tjeb/Mailbox-Alert/issues/55!

**Comment by tjeb** [comment]
Sorry, no addition of #55 for now. I have no time to work on features in the foreseeable future.

**Comment by siffegh** [comment]
> Sorry, no addition of #55 for now. I have no time to work on features in the foreseeable future.

Thanks - take care of yourself.

**Pull request closed without merging**
