### PR TITLE
Initial WebExtension conversion step

### PR DESCRIPTION
**Pull request by jobisoft**
In order to move this add-on forward, it needs to switch to the WebExtension locale system, otherwise you would not be able to create menu entries in the background using the menus API, since there you cannot access the legacy locale system.

This PR follows the update tutorial posted here 3 years ago:
https://github.com/thundernest/addon-developer-support/wiki/Tutorial:-Switch-to-the-WebExtension-i18n-locale-system

After this PR has been merged, you can create menu entries in the context menu of the folder pane and use the notify tools to signal into your legacy code.

This PR also fixes a few things I found while updating the add-on.

I think everything works (in TB 102), but please double-check. :-)

### CODE REVIEW

**Comment by EnigmaPatrick** [comment]
I've had a quick check and it looks like it works in 102, but needs more work for 115 as issue is still present

**Comment by jobisoft** [comment]
This is not the needed conversion for 115. This is the locale conversion, so you can use the menus API in the background, which you need for the folder pane menu in 115.

Edit: manifest has still `"strict_max_version": "102.*"`

**Comment by jobisoft** [comment]
Please see also my response on topicbox:
https://thunderbird.topicbox.com/groups/addons/T6d6b03b89517adfd-M563c3c0af9104f767ae918d0

**Comment by EnigmaPatrick** [comment]
Oh! I misread your post sorry!

**Pull request merged**
